-- Миграция для расширения модели Order (v2)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS external_number VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS source VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS comment TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS bonus_accrued NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_with_discount NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier_name VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS iiko_creation_time TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS expected_time TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS actual_time TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delay_minutes INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_on_time BOOLEAN DEFAULT TRUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_name VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_zone VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_items_details JSON;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discounts_details JSON;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_info_details JSON;

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS ix_orders_external_number ON orders (external_number);
