server {
    listen 80;
    server_name 72roll.ru www.72roll.ru;

    # ACME Challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Temporary allow HTTP access
    location /api {
        proxy_pass http://foodtech-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin {
        alias /var/www/html/admin/public;
        try_files $uri $uri/ @admin_laravel;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_pass foodtech-admin:9000;
        }
    }

    location @admin_laravel {
        rewrite /admin/(.*)$ /admin/index.php?/$1 last;
    }

    location / {
        proxy_pass http://foodtech-frontend:80;
        proxy_set_header Host $host;
    }
}
