"""Add shift stats

Revision ID: f3e3c0b1e6c7
Revises: 7e2b1c3d4a1b
Create Date: 2026-04-16 05:33:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'f3e3c0b1e6c7'
down_revision = '7e2b1c3d4a1b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('cancelled_orders_count', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('revenue_at_close', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'revenue_at_close')
    op.drop_column('shifts', 'cancelled_orders_count')
    # ### end Alembic commands ###
