
ALTER TABLE customers ADD COLUMN IF NOT EXISTS middle_name VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS referrer VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS registration_source VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS registered_organization VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS iiko_card_numbers JSONB DEFAULT '[]';
ALTER TABLE customers ALTER COLUMN gender TYPE VARCHAR(50);
